### PR TITLE
unify launch files and update files accordingly

### PR DESCRIPTION
**Pull request by YueErro**
Updates related to:
- unused/deprecated files [#1876](https://github.com/erlerobot/management/issues/1876)
- Readme.md [#1844 (comment)](https://github.com/erlerobot/management/issues/1844#issuecomment-489024150)

### CODE REVIEW

**Comment by rkojcev** [comment]
Don't merge yet

**Comment by alesolano** [comment]
I'm going to test it

**Comment by YueErro** [comment]
Please, remove gripper_interface.py and mara_joint_control.py from [mara_utils_scripts/scripts](https://github.com/AcutronicRobotics/MARA/tree/launch/mara_utils_scripts/scripts) and [mara_with_moveit_bridge.launch.py](https://github.com/AcutronicRobotics/MARA/blob/launch/mara_gazebo/launch/mara_with_moveit_bridge.launch.py) in case they are deprecated.

**Comment by rkojcev** [comment]
Tested and works fine. great job @YueErro l like a lot these changes.

**Comment by alesolano** [comment]
it's not working for me for now. wait a sec please

**Comment by alesolano** [comment]
ok fine from me side as well

**Pull request merged**
