### PR TITLE
Update HRIM related names

### PR DESCRIPTION
**Pull request by YueErro**

### CODE REVIEW

**Comment by rkojcev** [comment]
@YueErro you need to resolve the conflicts before we can merge.

**Comment by LanderU** [comment]
Fix the conflicts please!

**Comment by ahcorde** [comment]
we should only commit the naming change -> hrim_actuation to hrim_actuator

**Comment by YueErro** [comment]
Alright will create a new PR with the following changes:
From:
- /hrim_actuation_servomotor_MAC
- /hrim_actuation_gripper_MAC

To:
- /hrim_**actuator_rotaryservo**_MAC
- /hrim_**actuator_gripper**_MAC

**Pull request closed without merging**
