### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LanderU**
Added gazebo dependency

### CODE REVIEW

**Comment by nzlz** [comment]
I believe this dependency installs gazebo 9.0.0, can you check that? some packages require of newer versions to work (I'm afraid right now I can't remember which or what, but I'm sure I have seen this issue).

I think it would be a better idea to install gazebo using the [one liner installation](http://gazebosim.org/tutorials?tut=install_ubuntu#Defaultinstallation:one-liner), which provides the latest version:
```
curl -sSL http://get.gazebosim.org | sh
```

Note: If you want to keep the installation this way, you must first set your computer to accept sources from osrf:

```
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'```

**Comment by LanderU** [comment]
In my case it installs 9.6.0. Is this the correct one?

**Comment by nzlz** [comment]
> In my case it installs 9.6.0. Is this the correct one?

Yep, I guess its fine then. Will test it in a clean machine when I have some time just in case.

**Comment by LanderU** [comment]
Thanks @nzlz, regarding to sources.list, I'll include this in the instructions as well.

**Pull request closed without merging**
