### PR TITLE
update gazebo_ros_pkgs to crystal

### PR DESCRIPTION
**Pull request by YueErro**
Same as image common, it seems to fail under ros2.

### CODE REVIEW

**Comment by ibaiape** [comment]
+1, with current **ros2** branch the compilation fails with:
```
--- stderr: gazebo_ros                                
/mnt/Datos/workspace/ros2_mara_latest/src/gazebo_ros_pkgs/gazebo_ros/src/node.cpp: In static member function ‘static gazebo_ros::Node::SharedPtr gazebo_ros::Node::Get(sdf::ElementPtr)’:
/mnt/Datos/workspace/ros2_mara_latest/src/gazebo_ros_pkgs/gazebo_ros/src/node.cpp:80:3: error: ‘NodeOptions’ is not a member of ‘rclcpp’
   rclcpp::NodeOptions node_options;
   ^
/mnt/Datos/workspace/ros2_mara_latest/src/gazebo_ros_pkgs/gazebo_ros/src/node.cpp:81:3: error: ‘node_options’ was not declared in this scope
   node_options.arguments(arguments);
   ^
make[2]: *** [CMakeFiles/gazebo_ros_node.dir/src/node.cpp.o] Error 1
make[1]: *** [CMakeFiles/gazebo_ros_node.dir/all] Error 2
make: *** [all] Error 2
---
```

**Comment by LanderU** [comment]
Yep, you need to use crystal release.

**Comment by LanderU** [comment]
LGTM!

**Comment by rkojcev** [comment]
@nzlz you mentioned this morning something about updating docker?

**Comment by LanderU** [comment]
> @nzlz you mentioned this morning something about updating docker?

Let me know what you need. I can take care of this.

**Comment by nzlz** [comment]
Not related to this PR. But since we are changing the gazebo_ros_pkgs branch, can we start using :

```
  gazebo_ros_pkgs:
    type: git
    url: https://github.com/acutronicrobotics/gazebo_ros_pkgs
    version: ros2_gym-gazebo

```

Ill try to make a PR with the ai changes today.

**Pull request merged**
