### PR TITLE
Mara repos

### PR DESCRIPTION
**Pull request by LanderU**

### CODE REVIEW

**Comment by LanderU** [comment]
I think with `mara-ros2.repos` is more easy to maintain/switch the repo. Is only a suggestion.

**Comment by vmayoral** [comment]
+1 for this. I quite like it this way.

Furthermore, we should probably consider separating the existing packages into different repositories.

**Comment by ahcorde** [comment]
Let's me try it before we will merge it.

**Comment by ahcorde** [comment]
We also need to change docs. It's on me

**Comment by LanderU** [comment]
Any chance to get this merge? Is anything pending? Shall I create a PR adding the new installation instructions on docs?

**Pull request merged**
