### PR TITLE
updating readme related to ROS1/2 bridge

### PR DESCRIPTION
**Pull request by alesolano**

### CODE REVIEW

**Comment by alesolano** [comment]
don't merge yet. may be more readme updates to come

**Comment by LanderU** [comment]
Are we ready to merge it?

**Comment by alesolano** [comment]
wait a sec

**Comment by alesolano** [comment]
not very readme but

**Comment by alesolano** [comment]
I prefer using python2 since it works fine from the beginning without needing to install anything additional.

If we want to change it to python3 (I don't see any advantages) we would need to add the next lines in the dependencies as mentioned here https://github.com/erlerobot/management/issues/1844#issuecomment-488585373
```
sudo apt install python3-pip # if not done previously for HRIM
pip3 install catkin_pkg rospkg pyyaml
```

Any opinions on this @rkojcev @nzlz @ahcorde  ?

**Comment by rkojcev** [comment]
Lets stick to python2 for ROS 1 related matters. I do not see the advantage of having python3 in ROS 1 and installing additionally things that potentially break or remove other packages.

**Comment by alesolano** [comment]
nothing more to add to this PR from my side

**Pull request merged**
