### PR TITLE
rename file

### PR DESCRIPTION
**Pull request by YueErro**
Renaming the file in order not to confuse people. This is not AI related launch.

### CODE REVIEW

**Comment by nzlz** [comment]
hros_cognition_mara_components Node should be removed if this is for the real robot. Also, are you using the robot_state_publisher for something?

**Comment by rkojcev** [comment]
dont merge, @nzlz review please

**Comment by nzlz** [comment]
Last time I checked with @ahcorde I believe we talked about `robot_state_publisher` was not being used. Can @ahcorde @LanderU confirm this? If we are not using cognition or state publisher in the real robot, we can completely remove the `mara_bringup` ros package.

**Comment by igorrecioh** [comment]
**AFAIK, we use this for real MARA:**
```bash
roslaunch mara_bringup mara_bringup_moveit_actions.launch
```

**Here the code of mara_bringup_moveit_actions.launch:**

```xml
<?xml version="1.0"?>
<launch>

  <arg name="prefix" default="140"/>

  <param name="robot_description" command="$(find xacro)/xacro --inorder '$(find mara_description)/urdf/mara_robot_gripper_$(arg prefix).urdf.xacro'" />

  <!-- Robot state publisher -->
  <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
    <param name="publish_frequency" type="double" value="50.0" />
    <param name="tf_prefix" type="string" value="" />
  </node>

  <node pkg="mara_bringup" type="follow_joints_trajectory_actions.py" name="follow_joints_individual_trajectory" args="$(find mara_bringup)/config/motors.yaml">
  </node>

  <include file="$(find mara_moveit_config)/launch/mara_moveit_planning_execution.launch">
  </include>

  <include file="$(find mara_moveit_config)/launch/moveit_rviz.launch">
    <arg name="config" default="true"/>
  </include>

</launch>```

So I would say that we use robot_state_publisher. Let's wait until @ahcorde confirms it but...

**Comment by rkojcev** [comment]
ok then lets just rename this and leave the other part untouched.

**Pull request merged**
