### PR TITLE
Added travis:

### PR DESCRIPTION
**Pull request by LanderU**
* Create .ci folder with Dockerfile to compile the repo
* Create .travis.yml file

### CODE REVIEW

**Comment by LanderU** [comment]
Reviewable.

**Comment by nzlz** [comment]
In `.ci/compile.sh ` I had to change the following:

```diff
- cp -r /tmp/MARA/* src/mara
+ mkdir -p /tmp/MARA
+ cp -r /tmp/MARA/ src/mara/*

```

**Comment by nzlz** [comment]
The compilation does not start until you enter the docker via `docker run`. Should this be changed?

Fixed a issue with `robotiq_gripper_gazebo_plugins` (https://github.com/AcutronicRobotics/robotiq_modular_gripper/commit/1a0c76dfe19792a3cf4206f64ecec2e07a8bf31a) and ROS2 WS its compiling fine now. (ros1 still not finished)

---
Im getting this error frequently before the entrypoint, Im solving it by retrying:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4.3_amd64.deb  Connection failed [IP: 91.189.91.23 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by LanderU** [comment]
> Update: I see you handle this in the travis.yml script via before_script. Was not working fine for me, seems like it works fine in the travis build though.

These commands are only for travis. In order to compile the current branch instead of compile only master that is set on .repos file.

> Im getting this error frequently before the entrypoint, Im solving it by retrying many times:
> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-> 2ubuntu4.3_amd64.deb  Connection failed [IP: 91.189.91.23 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

This is a known issue, see: http://wiki.ros.org/melodic/Installation/Ubuntu setup you keys. They provide the key in three different server. I'm going to implement a logic, to retry the fetch if one is failling(in a separate PR).

**Comment by LanderU** [comment]
I'm running again after fetch your latest changes on README.md @nzlz, if I've green light I'll merge it.

**Pull request merged**
