### PR TITLE
Update dashing

### PR DESCRIPTION
**Pull request by anasarrak**
Merging the latest changes, they have updated the mara_descriptions DAEs, it was taking too much time to lauch gazebo.

### CODE REVIEW

**Comment by LanderU** [comment]
There is an open PR in order to update to dashing: https://github.com/AcutronicRobotics/MARA/pull/95

**Comment by anasarrak** [comment]
Do we want to update master to only compile for dashing?

**Comment by LanderU** [comment]
We should create a release for crystal and maintain on master the dashing.

**Comment by anasarrak** [comment]
> We should create a release for crystal and maintain on master the dashing.
+1

**Comment by anasarrak** [comment]
Closing this then, thanks @LanderU

**Pull request closed without merging**
